[tool.poetry]
name = "immich-offline"
version = "0.1.0"
description = ""
authors = ["Dante Razo <dante@razonet.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
